apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      app: spring-boot
    name: sb-generator
  spec:
    replicas: 1
    selector:
      app: spring-boot
    template:
      metadata:
        name: spring-boot
        labels:
          app: spring-boot
      spec:
        containers:
        - name: sb-generator
          image: quay.io/snowdrop/spring-boot-generator:latest
          ports:
          - containerPort: 8080
          env:
          - name: SERVER_PORT
            value: '8080'
          - name: GENERATOR_PATH
            value: '/opt/generator'
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: spring-boot
    name: spring-boot
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8080
    type: ClusterIP
    selector:
      app: spring-boot
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: spring-boot
    name: spring-boot
  spec:
    port:
      targetPort: 8000-tcp
    to:
      kind: Service
      name: spring-boot